# Generated by Django 4.1.4 on 2022-12-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
    ]
